"use client";
import { useRef, useState } from "react";
import { Camera, ImagePlus } from "lucide-react";
import { compressProductImage, MAX_IMAGE_SIZE } from "@/_lib/image-client";
export function ProductPhotoUpload({ produitId, initialUrl, onPrepared, onUploaded }: { produitId?: string; initialUrl?: string | null; onPrepared?: (file: File) => void; onUploaded?: (url: string) => void }) {
 const ref=useRef<HTMLInputElement>(null); const [preview,setPreview]=useState(initialUrl??""); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 async function choose(file?:File) { if(!file)return; if(file.size>MAX_IMAGE_SIZE)return setError("Image trop lourde : 5 Mo maximum."); setLoading(true); setError(""); try { const image=await compressProductImage(file); setPreview(URL.createObjectURL(image)); if(!produitId)return onPrepared?.(image); const fd=new FormData();fd.append("photo",image);const r=await fetch(`/api/marketplace/produits/${produitId}/photo`,{method:"POST",body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error);const u=await fetch(`/api/marketplace/produits/${produitId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({photoUrl:j.data.publicUrl})});if(!u.ok)throw new Error("Photo non enregistr?e");setPreview(j.data.publicUrl);onUploaded?.(j.data.publicUrl); } catch(e){setError(e instanceof Error?e.message:"Envoi impossible");} finally{setLoading(false);} }
 return <div className="rounded-2xl border border-dashed border-primary/30 bg-primary/5 p-4 space-y-3">{preview&&<img src={preview} alt="Aper?u produit" className="h-40 w-full rounded-xl object-cover"/>}<input ref={ref} type="file" accept="image/jpeg,image/png,image/webp" capture="environment" className="hidden" onChange={e=>choose(e.target.files?.[0])}/><button type="button" className="btn btn-outline btn-primary w-full" disabled={loading} onClick={()=>ref.current?.click()}>{loading?<span className="loading loading-spinner loading-sm"/>:preview?<Camera size={18}/>:<ImagePlus size={18}/>}{loading?"Pr?paration / envoi...":preview?"Changer la photo":"Ajouter une photo"}</button>{error&&<p className="text-xs text-error">{error}</p>}<p className="text-xs text-muted">JPG, PNG ou WebP, 5 Mo max. Image optimis?e avant l'envoi.</p></div>;
}
